<?xml version="1.0"?>
<!--~
  ~ @package   AkeebaDataCompliance
  ~ @copyright Copyright (c)2018-2025 Nicholas K. Dionysopoulos / Akeeba Ltd
  ~ @license   GNU General Public License version 3, or later
  -->

<project name="DataCompliance" description="DataCompliance for Joomla" default="git" >
    <import file="${phing.dir}/../buildfiles/phing/common.xml" />

	<!--
	====================================================================================================
	File sets
	====================================================================================================
	-->
	<fileset dir="${dirs.component}" id="component" expandsymboliclinks="true">
		<include name="**" />

        <exclude name="backend/views/**" />
        <exclude name="frontend/views/**" />
	</fileset>

    <fileset dir="${dirs.release}" id="package">
        <include name="com_*.zip" />
        <include name="file_*.zip" />
        <include name="mod_*.zip" />
        <include name="plg_*.zip" />
        <include name="lib_*.zip" />
        <include name="pkg_*.xml" />
        <include name="language/**"/>
        <include name="*.txt" />
        <include name="script.*.php" />
    </fileset>

    <!--
    ====================================================================================================
    Tasks - General
    ====================================================================================================
    -->

    <target name="git" description="Makes only packages, not the documentation"
            depends="new-release,setup-properties,compile-javascript,compile-css,component-packages">
    </target>

    <target name="documentation" description="Creates the documentation packages" depends="doc-epub">
    </target>

    <target name="doc-epub" description="Documentation for Joomla! in PDF format">
        <phingcall target="docbook-epub">
            <property name="docs.input" value="datacompliance.xml" />
        </phingcall>
    </target>

    <target name="docsdeploy">
        <phingcall target="docbook-zip">
            <property name="docs.input" value="datacompliance.xml" />
        </phingcall>

        <property name="docsdeploy.path.source" value="datacompliance-import.zip"/>
        <property name="docsdeploy.path.target" value="datacompliance"/>

        <curlsftp
                host="${scp.host}"
                port="${scp.port}"
                username="${scp.username}"
                password="${scp.password}"
                pubkeyfile="${scp.pubkeyfile}"
                privkeyfile="${scp.privkeyfile}"
                privkeyfilepassphrase="${scp.privkeyfilepassphrase}"
                todir="${scp.dir.docs}/${docsdeploy.path.target}"
                level="debug">
            <fileset dir="${dirs.release}">
                <include name="${docsdeploy.path.source}"/>
            </fileset>
        </curlsftp>
    </target>

    <target name="compile-javascript" description="Minify JavaScript files">
        <exec executable="node"
              dir="${dirs.root}/../buildfiles" checkreturn="true" passthru="true">
            <arg value="build-js.mjs" />
            <arg value="${dirs.component}/media/js" />
        </exec>
    </target>

    <target name="compile-css" description="Compile SCSS to minified CSS">
        <exec executable="sass" dir="${dirs.component}/media/css" checkreturn="true" passthru="true">
            <arg value="${dirs.component}/media/css:${dirs.component}/media/css" />
            <arg value="-s" />
            <arg value="compressed" />
        </exec>
    </target>
</project>